name: Release # description of this workflow, can be anything you want

# triggers when pushing a tag
on:
  push:
    tags:
      - '**'

jobs:
  release: # "release" is a job, you can name it anything you want
    runs-on: ubuntu-latest
    env:
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # reads history for commit changelog

      - uses: BigWigsMods/packager@master
